[primax"    # name of backend
# version = "1.1.beta1"                    # version of backend
# manpage = "sane-primax"           # name of manpage (if it exists)
url = "http://px-backend.sourceforge.net" # backend's web page
comment = "This backend is not included because it depends on the code of the primax command line program. Therefore the author wants to keep it in the primax CVS tree."

devicetype = "scanner"             # start of a list of devices....
                                 # other types:  :stillcam, :vidcam,
                                 #               :meta, :api

[mfg]
mfg = "Primax"                    # name a manufacturer
url = "http://www.primax.nl/"

[mfg.model]
model = "Colorado Direct 300"
interface = "Parport"
status = "good"

[mfg.model]
model = "Colorado Direct 600/30bit"
interface = "Parport"
status = "untested"

[mfg]
mfg = "Network"                   # another manufacturer...

[mfg.model]
model = "Scanny MM100"
interface = "Parport"
status = "good"

[mfg]
mfg = "Storm"

[mfg.model]
model = "Totalscan"
interface = "Parport"
status = "untested"

[mfg.model]
model = "ImageWave"
interface = "Parport"
status = "untested"

[mfg]
mfg = "Genius"

[mfg.model]
model = "Colorpage-Vivid+"
interface = "Parport"
status = "untested"
