[qcam"    # name of backend
version = "unmaintained"                    # version of backend
# url = ""                           # backend's homepage
manpage = "sane-qcam"

devicetype = "vidcam"

[mfg]
mfg = "Connectix"                    # name a manufacturer
# url = "http://www.connectix.com/"   # doesn't exist any longer?

[mfg.model]
model = "Color QuickCam"             # name models for above-specified mfg.
interface = "Parport"
status = "good"
comment = "Requires root privileges."

[mfg.model]
model = "Greyscale QuickCam"         # name models for above-specified mfg.
interface = "Parport"
status = "minimal"
comment = "Requires root privileges.  Partly working."
