[kodak"
url = "http://www.thebility.com/kodak/"
version = "7"
manpage = "sane-kodak"
comment = "New backend for SANE release 1.0.21, see sane-kodak manpage"
devicetype = "scanner"

[mfg]
mfg = "Kodak"
url = "http://www.kodak.com/"

# ======================================
# workgroup machines, old

[mfg.model]
model = "Scanner 1500"
interface = "SCSI"
status = "untested"
comment = "Please test!"

# ======================================
# departmental machines, old

[mfg.model]
model = "Scanner 2500"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Scanner 3500"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Scanner 3510"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Scanner 3520"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Color Scanner 3590C"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Color Scanner 4500"
interface = "SCSI"
status = "untested"
comment = "Please test!"

# ======================================
# departmental machines, recent

[mfg.model]
model = "i150 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i160 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i250 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i260 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i280 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

# ======================================
# production machines, old

[mfg.model]
model = "Scanner 900"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Scanner 923"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Scanner 5500"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Scanner 7500"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Scanner 7520"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Scanner 9500"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "Scanner 9520"
interface = "SCSI"
status = "untested"
comment = "Please test!"

# ======================================
# production machines, recent

[mfg.model]
model = "i610 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i620 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i640 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i660 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i730 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i750 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i780 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i810 Scanner"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i820 Scanner"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i830 Scanner"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i840 Scanner"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i1840 Scanner"
interface = "IEEE-1394"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "i1860 Scanner"
interface = "IEEE-1394"
status = "basic"
comment = "Uncompressed B&W, Gray and Color, some automatic features supported"

[mfg.model]
model = "s1740"
interface = "SCSI"
status = "untested"
comment = "Please test!"
