#
# SANE Backend description file for U12 backend
#

[backend]
backend = "u12"
version = "0.02"
manpage = "sane-u12"

devicetype = "scanner"

# * Plustek **********************************************************************************

[mfg]
mfg = "Plustek"
url = "http://www.plustek.de/"
url = "http://www.plustek.com/"

[mfg.model]
model = "OpticPro U12"
interface = "USB"
usbid = ["0x07b3", "0x0001"]
status = "basic"
comment = "Note: Only devices with product ID 0x0001 are supported!"

[mfg.model]
model = "OpticPro UT12"
interface = "USB"
usbid = ["0x07b3", "0x0001"]
status = "basic"
comment = "Note: Only devices with product ID 0x0001 are supported!"

[mfg.model]
model = "OpticPro 1212U"
interface = "USB"
usbid = ["0x07b3", "0x0001"]
status = "basic"

# * RevScan **********************************************************************************

[mfg]
mfg = "RevScan"

[mfg.model]
model = "RevScan Orange R48Ti"
interface = "USB"
usbid = ["0x07b3", "0x0001"]
status = "basic"
comment = "Rebadged Plustek OpticPro UT12"

# * Genius/KYE *******************************************************************************************

[mfg]
mfg = "Genius"
url = "http://www.geniusnet.com.tw/"

[mfg.model]
model = "ColorPage HR6 V1"
interface = "USB"
usbid = ["0x0458", "0x2004"]
status = "basic"

[mfg.model]
model = "ColorPage Vivid III USB"
interface = "USB"
usbid = ["0x07b3", "0x0001"]
status = "untested"
comment = "Note: Device has Plustek vendor and product ID (0x07b3/0x0001)"
