#
# SANE Backend specification file
#
# It's basically emacs-lisp --- so ";" indicates comment to end of line.
# All syntactic elements are keyword tokens, followed by a string or
#  keyword argument, as specified.
#
# ":backend" *must* be specified.
# All other information is optional (but what good is the file without it?).
#
# See doc/descriptions.txt for details.

[backend]
backend = "ricoh2"    # name of backend
version = "1.0"                    # version of backend (or "unmaintained")
manpage = "sane-ricoh2"            # name of manpage (if it exists)
url = "http://www.ricoh.com/"      # backend's web page

devicetype = "scanner"              # start of a list of devices....
                                  # other types:  :stillcam, :vidcam,
                                  #               :meta, :api

[mfg]
mfg = "Ricoh"                      # name a manufacturer
url = "http://www.ricoh.com/"      # manufacturer's URL

[mfg.model]
model = "SG-3100SFNw"
status = "basic"
interface = "USB"
usbid = ["0x05ca", "0x0439"]

[mfg.model]
model = "SG-3100SNw"
status = "basic"
interface = "USB"
usbid = ["0x05ca", "0x0438"]

[mfg.model]
model = "SP-100SU"
status = "untested"
interface = "USB"
usbid = ["0x05ca", "0x042c"]

[mfg.model]
model = "SP-111SU/SP-112SU"
status = "basic"
interface = "USB"
usbid = ["0x05ca", "0x0448"]
