#
# SANE Backend specification file
#
# It's basically emacs-lisp --- so ";" indicates comment to end of line.
# All syntactic elements are keyword tokens, followed by a string or
#  keyword argument, as specified.
#
# ":backend" *must* be specified.
# All other information is optional (but what good is the file without it?).


[backend]
backend = "lexmark"    # name of backend
version = "1.0-0 (unmaintained)"   # version of backend (or "unmaintained")
manpage = "sane-lexmark"           # name of manpage (if it exists)
url = "http://stef.dev.free.fr/sane/lexmark"
				  # backend's web page

comment = "This backend supports lexmark x1100 series scanners."
                                  # comment about the backend

devicetype = "scanner"              # start of a list of devices....
                                  # other types:  :stillcam, :vidcam,
                                  #               :meta, :api

[mfg.lexmark]
mfg = "Lexmark"                   # name a manufacturer
url = "http://www.lexmark.com/"   # manufacturer's URL

[mfg.lexmark.X1110]
model = "X1110"
interface = "USB"
usbid = ["0x043d", "0x007c"]
status = "untested"

[mfg.lexmark.X1130]
model = "X1130"
interface = "USB"
usbid = ["0x043d", "0x007c"]
status = "good"
comment = "Supports 75, 150, 300, 600 dpi"

[mfg.lexmark.X1140]
model = "X1140"
interface = "USB"
usbid = ["0x043d", "0x007c"]
status = "untested"

[mfg.lexmark.X1150]
model = "X1150"
interface = "USB"
usbid = ["0x043d", "0x007c"]
status = "good"
comment = "Supports 75, 150, 300, 600 dpi"

[mfg.lexmark.X1170]
model = "X1170"
interface = "USB"
usbid = ["0x043d", "0x007c"]
status = "good"
comment = "Supports 75, 150, 300, 600 dpi"

[mfg.lexmark.X1180]
model = "X1180"
interface = "USB"
usbid = ["0x043d", "0x007c"]
status = "good"

[mfg.lexmark.X1185]
model = "X1185"
interface = "USB"
usbid = ["0x043d", "0x007c"]
status = "good"
comment = "Tested with xscanimage. Supports 75, 150, 300, 600, 1200(600x1200) dpi resolutions. Does grayscale or colour scans in the following sizes: wallet, 3x5, 4x6, 5x7, 8x10, letter."

[mfg.lexmark.X1195]
model = "X1195"
interface = "USB"
usbid = ["0x043d", "0x007c"]
status = "untested"

[mfg.lexmark.X74]
model = "X74"
interface = "USB"
usbid = ["0x043d", "0x0060"]
status = "good"
comment = "Supports 75, 150, 300, 600 dpi"

[mfg.lexmark.X12xx]
model = "X12xx"
interface = "USB"
usbid = ["0x043d", "0x007d"]
status = "good"
comment = "USB1.1 is OK, USB2.0 needs testing"

[mfg.dell]
mfg = "Dell"                   # name a manufacturer
[mfg.dell.A920]
model = "A920"
interface = "USB"
usbid = ["0x413c", "0x5105"]
status = "good"
comment = "Relabelled X11xx model"
