#
# SANE Backend specification file
#
# It's basically emacs-lisp --- so ";" indicates comment to end of line.
# All syntactic elements are keyword tokens, followed by a string or
#  keyword argument, as specified.
#
# ":backend" *must* be specified.
# All other information is optional (but what good is the file without it?).
#


[backend]
backend = "fujitsu"    # name of backend
url = "http://www.thebility.com/fujitsu/"
version = "134"                   # version of backend
manpage = "sane-fujitsu"          # name of manpage (if it exists)
comment = "Backend updated for SANE release 1.0.28, see sane-fujitsu manpage"
devicetype = "scanner"             # start of a list of devices....
                                 # other types:  :stillcam, :vidcam,
                                 #               :meta, :api

[mfg]
mfg = "Fujitsu"                   # name a manufacturer
url = "http://www.fujitsu.com/"

# ==================================================
# DISCONTINUED OLDER MODELS, SMALL
[mfg.model]
model = "M3091DC"
interface = "SCSI"
url = "http://www.remote.org/frederik/projects/software/sane/"
status = "complete"
comment = "small, old, discontinued"

[mfg.model]
model = "M3092DC"
interface = "SCSI"
status = "complete"
comment = "small, old, discontinued"

# ==================================================
# DISCONTINUED NEWER MODELS, SMALL
[mfg.model]
model = "fi-4120C"
interface = "SCSI USB"
usbid = ["0x04c5", "0x1041"]
status = "complete"
comment = "small, recent, discontinued, usb 1.1"

[mfg.model]
model = "fi-4120C2"
interface = "SCSI USB"
usbid = ["0x04c5", "0x10ae"]
status = "complete"
comment = "small, recent, discontinued, usb 2.0"

[mfg.model]
model = "fi-4220C"
interface = "SCSI USB"
usbid = ["0x04c5", "0x1042"]
status = "complete"
comment = "small, recent, discontinued, usb 1.1"

[mfg.model]
model = "fi-4220C2"
interface = "SCSI USB"
usbid = ["0x04c5", "0x10af"]
status = "complete"
comment = "small, recent, discontinued, usb 2.0"

[mfg.model]
model = "fi-5110C"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x1097"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-5110EOX/2"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x1096"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-5110EOX3"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x10e6"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-5110EOXM"
interface = "USB"
usbid = ["0x04c5", "0x10f2"]
status = "complete"
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-5120C"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x10e0"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-5220C"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x10e1"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-5000N"
interface = "Ethernet"
status = "untested"
comment = "Not a scanner, rather a scanner to ethernet interface"

[mfg.model]
model = "fi-6000NS"
interface = "Ethernet"
status = "untested"
comment = "small, recent, discontinued, integrated touchscreen and keyboard"

[mfg.model]
model = "ScanSnap S500"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x10fe"]
comment = "small, recent, discontinued"

[mfg.model]
model = "ScanSnap S500M"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x1135"]
comment = "small, recent, discontinued"

[mfg.model]
model = "ScanSnap S510"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x1155"]
comment = "small, recent, discontinued"

[mfg.model]
model = "ScanSnap S510M"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x116f"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-6130"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x114f"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-6230"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x1150"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-6130Z"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x11f3"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-6230Z"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x11f4"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-6120ZLA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x146d"]
comment = "small, recent, discontinued, expected to work"

[mfg.model]
model = "fi-6220ZLA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x146e"]
comment = "small, recent, discontinued, expected to work"

[mfg.model]
model = "fi-6125ZLA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x1463"]
comment = "small, recent, discontinued, expected to work"

[mfg.model]
model = "fi-6225ZLA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x1464"]
comment = "small, recent, discontinued, expected to work"

[mfg.model]
model = "fi-6130ZLA"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x1461"]
comment = "small, recent, discontinued"

[mfg.model]
model = "fi-6230ZLA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x1462"]
comment = "small, recent, discontinued, expected to work"

[mfg.model]
model = "ScanSnap S1500"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x11a2"]
comment = "small, discontinued"

[mfg.model]
model = "ScanSnap S1500M"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x11a2"]
comment = "small, discontinued, same as S1500"

[mfg.model]
model = "ScanSnap N1800"
interface = "Ethernet"
status = "untested"
comment = "small, discontinued, integrated touchscreen and keyboard"

# ==================================================
# CURRENT MODELS, SMALL
[mfg.model]
model = "ScanSnap N7100"
interface = "Ethernet"
status = "untested"
comment = "small, current, integrated touchscreen and keyboard"

[mfg.model]
model = "ScanSnap fi-6010N"
interface = "Ethernet"
status = "untested"
comment = "small, current, integrated touchscreen and keyboard"

[mfg.model]
model = "fi-6110"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x11fc"]
comment = "small, current"

[mfg.model]
model = "fi-7160"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x132e"]
comment = "small, current"

[mfg.model]
model = "fi-7260"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x132f"]
comment = "small, current"

[mfg.model]
model = "ScanSnap iX500"
interface = "USB WiFi"
status = "good"
usbid = ["0x04c5", "0x132b"]
comment = "small, current, WiFi not supported. Hardware only scans in color. Backend generates binary and grayscale modes."

[mfg.model]
model = "ScanSnap iX100"
interface = "USB WiFi"
status = "good"
usbid = ["0x04c5", "0x13f4"]
comment = "small, current, WiFi not supported."

[mfg.model]
model = "ScanSnap SV600"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x128e"]
comment = "Also has a second USB VID 0x13ba. Will require some gymnastics to support."

# ==================================================
# DISCONTINUED OLDER MODELS, MEDIUM
[mfg.model]
model = "M3093E"
interface = "RS232C/Video"
status = "unsupported"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3093DE"
interface = "RS232C/Video"
status = "unsupported"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3093DG"
interface = "SCSI"
status = "complete"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3093EX"
interface = "RS232C/Video"
status = "unsupported"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3093GX"
interface = "SCSI"
status = "complete"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3096EX"
interface = "RS232C/Video"
status = "unsupported"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3096GX"
interface = "SCSI"
status = "complete"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3097E+"
interface = "RS232C/Video"
status = "unsupported"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3097G+"
interface = "SCSI"
status = "complete"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3097DE"
interface = "RS232C/Video"
status = "unsupported"
comment = "medium, old, discontinued"

[mfg.model]
model = "M3097DG"
interface = "SCSI"
status = "complete"
comment = "medium, old, discontinued"

# ==================================================
# DISCONTINUED NEWER MODELS, MEDIUM
[mfg.model]
model = "fi-4340C"
interface = "SCSI USB"
usbid = ["0x04c5", "0x10cf"]
status = "complete"
comment = "medium, current"

[mfg.model]
model = "fi-4530C"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x1078"]
comment = "medium, recent, discontinued"

[mfg.model]
model = "fi-4640S"
interface = "SCSI"
status = "complete"
comment = "medium, recent, discontinued"

[mfg.model]
model = "fi-4750C"
interface = "SCSI"
status = "complete"
comment = "medium, recent, discontinued"

[mfg.model]
model = "fi-5530C"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x10e2"]
comment = "medium, recent, discontinued"

[mfg.model]
model = "fi-6140"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x114d"]
comment = "medium, recent, discontinued"

[mfg.model]
model = "fi-6240"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x114e"]
comment = "medium, recent, discontinued"

[mfg.model]
model = "fi-6140Z/fi-6140ZLA"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x11f1"]
comment = "medium, recent, discontinued"

[mfg.model]
model = "fi-6240Z"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x11f2"]
comment = "medium, recent, discontinued"

[mfg.model]
model = "fi-6135ZLA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x146b"]
comment = "medium, recent, discontinued, expected to work"

[mfg.model]
model = "fi-6235ZLA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x146c"]
comment = "medium, recent, discontinued, expected to work"

[mfg.model]
model = "fi-6140ZLA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x145f"]
comment = "medium, recent, discontinued, expected to work"

[mfg.model]
model = "fi-6240ZLA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x1460"]
comment = "medium, recent, discontinued, expected to work"

# ==================================================
# CURRENT MODELS, MEDIUM

[mfg.model]
model = "fi-5530C2"
interface = "SCSI USB"
status = "complete"
usbid = ["0x04c5", "0x114a"]
comment = "medium, current"

[mfg.model]
model = "fi-7180"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x132c"]
comment = "medium, current"

[mfg.model]
model = "fi-7280"
interface = "USB"
status = "complete"
usbid = ["0x04c5", "0x132d"]
comment = "medium, current"

# ==================================================
# DISCONTINUED OLDER MODELS, BIG
[mfg.model]
model = "M3099A"
interface = "RS232C/Video"
status = "unsupported"
comment = "big, old, discontinued"

[mfg.model]
model = "M3099G"
interface = "SCSI"
status = "complete"
comment = "big, old, discontinued"

[mfg.model]
model = "M3099EH"
interface = "RS232C/Video"
status = "unsupported"
comment = "big, old, discontinued"

[mfg.model]
model = "M3099GH"
interface = "SCSI"
status = "complete"
comment = "big, old, discontinued"

[mfg.model]
model = "M3099EX"
interface = "RS232C/Video"
status = "unsupported"
comment = "big, old, discontinued"

[mfg.model]
model = "M3099GX"
interface = "SCSI"
status = "complete"
comment = "big, old, discontinued"

[mfg.model]
model = "M4097D"
interface = "SCSI"
status = "complete"
comment = "big, old, discontinued"

[mfg.model]
model = "M4099D"
interface = "SCSI"
status = "complete"
comment = "big, old, discontinued"

# ==================================================
# DISCONTINUED NEWER MODELS, BIG
[mfg.model]
model = "fi-4750L"
interface = "SCSI"
status = "complete"
comment = "big, recent, discontinued"

[mfg.model]
model = "fi-4860C"
interface = "SCSI"
status = "complete"
comment = "big, recent, discontinued"

[mfg.model]
model = "fi-4860C2"
interface = "SCSI"
status = "complete"
comment = "big, recent, discontinued"

[mfg.model]
model = "fi-4990C"
interface = "SCSI"
status = "complete"
comment = "big, recent, discontinued"

[mfg.model]
model = "fi-5650C"
interface = "SCSI USB"
usbid = ["0x04c5", "0x10ad"]
status = "complete"
comment = "big, recent, discontinued"

[mfg.model]
model = "fi-5750C"
interface = "SCSI USB"
usbid = ["0x04c5", "0x1095"]
status = "complete"
comment = "big, recent, discontinued"

[mfg.model]
model = "fi-5900C"
interface = "SCSI USB"
usbid = ["0x04c5", "0x10e7"]
status = "good"
comment = "big, recent, discontinued. Independent ultrasonic control and multistream unsupported"

[mfg.model]
model = "fi-6750S"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x1178"]
comment = "Simplex, USB only version of fi-6770, won't wakeup via software, discontinued"

# ==================================================
# CURRENT MODELS, BIG
[mfg.model]
model = "fi-5950"
interface = "SCSI USB"
usbid = ["0x04c5", "0x1213"]
status = "untested"
comment = "big, current. Faster version of fi-5900?"

[mfg.model]
model = "fi-6670"
interface = "SCSI USB"
status = "good"
usbid = ["0x04c5", "0x1176"]
comment = "big, current, won't wakeup via software"

[mfg.model]
model = "fi-6670A"
interface = "SCSI USB"
status = "good"
usbid = ["0x04c5", "0x1177"]
comment = "big, current, VRS CGA board unsupported, won't wakeup via software"

[mfg.model]
model = "fi-6770"
interface = "SCSI USB"
status = "good"
usbid = ["0x04c5", "0x1174"]
comment = "big, current, won't wakeup via software"

[mfg.model]
model = "fi-6770A"
interface = "SCSI USB"
status = "good"
usbid = ["0x04c5", "0x1175"]
comment = "big, current, VRS CGA board unsupported, won't wakeup via software"

[mfg.model]
model = "fi-6800"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x119d"]
comment = "big, current. Independent ultrasonic control and multistream unsupported"

[mfg.model]
model = "fi-6800-CGA"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x119e"]
comment = "big, current. VRS CGA board unsupported, Independent ultrasonic control and multistream unsupported"

[mfg.model]
model = "fi-6400"
interface = "SCSI USB"
status = "good"
usbid = ["0x04c5", "0x14ac"]

# ==================================================
# 2015/2016/2017 NEW MODELS, UNORDERED

[mfg.model]
model = "fi-6420"
interface = "SCSI USB"
status = "untested"
usbid = ["0x04c5", "0x14bd"]

[mfg.model]
model = "ScanSnap iX500EE"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x13f3"]

[mfg.model]
model = "N7100"
interface = "USB Ethernet"
status = "untested"
usbid = ["0x04c5", "0x146f"]

[mfg.model]
model = "fi-7480"
interface = "USB"
status = "good"
usbid = ["0x04c5", "0x14b8"]

[mfg.model]
model = "fi-7460"
interface = "USB"
status = "good"
usbid = ["0x04c5", "0x14be"]

[mfg.model]
model = "fi-7140"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14df"]

[mfg.model]
model = "fi-7240"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14e0"]

[mfg.model]
model = "fi-7135"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14e1"]

[mfg.model]
model = "fi-7235"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14e2"]

[mfg.model]
model = "fi-7130"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14e3"]

[mfg.model]
model = "fi-7230"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14e4"]

[mfg.model]
model = "fi-7125"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14e5"]

[mfg.model]
model = "fi-7225"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14e6"]

[mfg.model]
model = "fi-7120"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14e7"]

[mfg.model]
model = "fi-7220"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x14e8"]

[mfg.model]
model = "fi-400F"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x151e"]

[mfg.model]
model = "fi-7030"
interface = "USB"
status = "good"
usbid = ["0x04c5", "0x151f"]

[mfg.model]
model = "fi-7700"
interface = "USB"
status = "good"
usbid = ["0x04c5", "0x1520"]

[mfg.model]
model = "fi-7600"
interface = "USB"
status = "good"
usbid = ["0x04c5", "0x1521"]

[mfg.model]
model = "fi-7700S"
interface = "USB"
status = "untested"
usbid = ["0x04c5", "0x1522"]

[mfg.model]
model = "ScanSnap iX1500"
interface = "USB WiFi"
status = "good"
usbid = ["0x04c5", "0x159f"]
comment = "small, current, WiFi not supported."

[mfg.model]
model = "fi-800R"
interface = "USB"
status = "good"
usbid = ["0x04c5", "0x15fc"]
comment = "small, current, both feed methods are supported."

[mfg.model]
model = "fi-7900"
interface = "USB"
status = "good"
usbid = ["0x04c5", "0x160a"]

[mfg.model]
model = "fi-7800"
interface = "USB"
status = "good"
usbid = ["0x04c5", "0x160b"]
