# SANE Backend specification file (Matto Marjanovic's format)
#
# It's basically emacs-lisp --- so ";" indicates comment to end of line.
# All syntactic elements are keyword tokens, followed by a string or
#  keyword argument, as specified.
#
# ":backend" *must* be specified.
# All other information is optional (but what good is the file without it?).
#

[backend]
backend = "SnapScan"               	# name of backend
version = "1.4"                    	# version of backend
manpage = "sane-snapscan"          	# name of manpage (if it exists)
url = "http://snapscan.sourceforge.net/" # backend's web page
comment = "Supported  bit depths: 24 bit (color), 48 bit (color, Epson) 8 bit (gray)"

devicetype = "scanner"              	# start of a list of devices....
                                  	# other types:  :stillcam, :vidcam,
                                  	#               :meta, :api

# -----------------------------------------------------------------------------

[mfg]
mfg = "AGFA"				# name a manufacturer
url = "http://www.agfa.com/"

[mfg.model]
model = "SnapScan"                  	# name models for above-specified mfg.
interface = "SCSI"
status = "good"

[mfg.model]
model = "SnapScan 300"
interface = "SCSI"
status = "good"

[mfg.model]
model = "SnapScan 310"
interface = "SCSI"
status = "good"

[mfg.model]
model = "SnapScan 600"
interface = "SCSI"
status = "good"
comment = "Optional ADF supported."

[mfg.model]
model = "Arcus 1200"
interface = "SCSI"
status = "good"
comment = "Optional transparency unit supported."

[mfg.model]
model = "SnapScan 1236s"
interface = "SCSI"
status = "good"
comment = "Optional ADF and transparency unit supported."

[mfg.model]
model = "SnapScan 1236u"
interface = "USB"
status = "good"
usbid = ["0x06bd", "0x0002"]
comment = "Optional ADF and transparency unit supported."

[mfg.model]
model = "SnapScan 1212U"
interface = "USB"
usbid = ["0x06bd", "0x0001"]
status = "good"

[mfg.model]
model = "SnapScan 1212U_2"
interface = "USB"
usbid = ["0x06bd", "0x2061"]
status = "good"

[mfg.model]
model = "SnapScan e10"
interface = "USB"
usbid = ["0x06bd", "0x2093"]
status = "good"

[mfg.model]
model = "SnapScan e20"
interface = "USB"
usbid = ["0x06bd", "0x2091"]
status = "good"

[mfg.model]
model = "SnapScan e25"
interface = "USB"
usbid = ["0x06bd", "0x2095"]
status = "good"

[mfg.model]
model = "SnapScan e26"
interface = "USB"
usbid = ["0x06bd", "0x2097"]
status = "good"

[mfg.model]
model = "SnapScan e40"
interface = "USB"
usbid = ["0x06bd", "0x208d"]
status = "good"

[mfg.model]
model = "SnapScan e42"
interface = "USB"
usbid = ["0x06bd", "0x20ff"]
status = "good"

[mfg.model]
model = "SnapScan e50"
interface = "USB"
status = "good"
usbid = ["0x06bd", "0x208f"]
comment = "Optional tranparency unit supported"

[mfg.model]
model = "SnapScan e52"
interface = "USB"
status = "good"
usbid = ["0x06bd", "0x20fd"]
comment = "Optional tranparency unit supported"

[mfg.model]
model = "SnapScan e60"
interface = "USB"
status = "untested"

# ------------------------------------------------------------------------------

[mfg]
mfg = "Acer Peripherals"
comment = "Company was renamed to <a href=\"#BENQ\">Benq</a>."

[mfg]
mfg = "Vuego"
comment = "Company was renamed to <a href=\"#BENQ\">Benq</a>."

[mfg]
mfg = "Benq (Acer)"
url = "http://www.benq.com"
comment = "Formerly Acer Peripherals"

[mfg.model]
model = "300f"
interface = "SCSI"
status = "good"

[mfg.model]
model = "310s"
interface = "SCSI"
status = "good"

[mfg.model]
model = "610s"
interface = "SCSI"
status = "good"

[mfg.model]
model = "610plus"
interface = "SCSI"
status = "good"

[mfg.model]
model = "620s"
interface = "SCSI"
status = "good"

[mfg.model]
model = "ScanWit 2720s"
interface = "SCSI"
status = "good"

[mfg.model]
model = "310U"
interface = "USB"
usbid = ["0x04a5", "0x1a20"]
status = "good"

[mfg.model]
model = "320U"
interface = "USB"
usbid = ["0x04a5", "0x2022"]
status = "good"

[mfg.model]
model = "340U"
interface = "USB"
usbid = ["0x04a5", "0x2022"]
status = "good"

[mfg.model]
model = "620U"
interface = "USB"
usbid = ["0x04a5", "0x1a2a"]
status = "good"
comment = "Optional tranparency unit supported"

[mfg.model]
model = "620UT"
interface = "USB"
usbid = ["0x04a5", "0x2040"]
status = "good"
comment = "Optional tranparency unit supported"


[mfg.model]
model = "640U"
interface = "USB"
usbid = ["0x04a5", "0x2060"]
status = "good"
comment = "Optional tranparency unit supported"

[mfg.model]
model = "640bu"
interface = "USB"
usbid = ["0x04a5", "0x207e"]
status = "good"

[mfg.model]
model = "640BT"
interface = "USB"
usbid = ["0x04a5", "0x20be"]
status = "good"
comment = "Optional tranparency unit supported"

[mfg.model]
model = "1240"
interface = "USB"
usbid = ["0x04a5", "0x20c0"]
status = "good"
comment = "Optional tranparency unit supported"

[mfg.model]
model = "3300"
interface = "USB"
usbid = ["0x04a5", "0x20b0"]
status = "good"

[mfg.model]
model = "3300"
interface = "USB"
usbid = ["0x04a5", "0x20de"]
status = "good"

[mfg.model]
model = "4300"
interface = "USB"
usbid = ["0x04a5", "0x20b0"]
status = "good"

[mfg.model]
model = "4300"
interface = "USB"
usbid = ["0x04a5", "0x20de"]
status = "good"

[mfg.model]
model = "5000E"
interface = "USB"
usbid = ["0x04a5", "0x20fc"]
status = "basic"
comment = "Same as 5000U, working up to 600 DPI"

[mfg.model]
model = "5000U"
interface = "USB"
usbid = ["0x04a5", "0x20fc"]
status = "basic"
comment = "Same as 5000E, working up to 600 DPI"

[mfg.model]
model = "5000"
interface = "USB"
usbid = ["0x04a5", "0x20f8"]
status = "good"
comment = "USB ID 0x04a5,0x20f8: Color / grayscale scans working up to 1200 DPI"

[mfg.model]
model = "5150"
interface = "USB"
usbid = ["0x04a5", "0x2137"]
status = "basic"
comment = "Calibration algorithm unknown"

[mfg.model]
model = "5250"
interface = "USB"
usbid = ["0x04a5", "0x2137"]
status = "basic"
comment = "Same hardware as 5150 (?), Calibration algorithm unknown"

[mfg.model]
model = "5300"
interface = "USB"
usbid = ["0x04a5", "0x20fe"]
status = "basic"
comment = "Problems with firmware upload reported"

# ------------------------------------------------------------------------------

[mfg]
mfg = "Guillemot / Hercules"
url = "http://www.guillemot.com"

[mfg.model]
model = "Maxi Scan A4 Deluxe (SCSI)"
interface = "SCSI"
status = "good"
comment = "Rebadged SnapScan 310s."

[mfg.model]
model = "Scan@home Touch 1248 (USB)"
interface = "USB"
usbid = ["0x04a5", "0x20de"]
status = "good"
comment = "Rebadged Benq 3300."

[mfg.model]
model = "Maxi Scan A4 USB 640U"
interface = "USB"
usbid = ["0x04a5", "0x2060"]
status = "good"
comment = "Rebadged Benq 640U."

[mfg.model]
model = "Maxi A4 36 bit"
interface = "USB"
usbid = ["0x04a5", "0x2060"]
status = "good"
comment = "Rebadged Benq 620U, needs Benq firmware file u96v???.bin"

# ------------------------------------------------------------------------------

[mfg]
mfg = "Mitsubishi"
url = "http://www.mitsubishi.com"

[mfg.model]
model = "Diamondview 648UT"
interface = "USB"
usbid = ["0x04a5", "0x2022"]
status = "good"
comment = "Rebadged Benq 320u."

[mfg.model]
model = "Diamondview 650U"
interface = "USB"
usbid = ["0x04a5", "0x20b0"]
status = "good"
comment = "Rebadged Benq 4300."

# ------------------------------------------------------------------------------

[mfg]
mfg = "Epson"
url = "http://www.epson.com"

[mfg.model]
model = "Perfection 660"
interface = "USB"
usbid = ["0x04b8", "0x0114"]
status = "good"
comment = "Requires firmware tail_058.bin."

[mfg.model]
model = "Perfection 1270"
interface = "USB"
usbid = ["0x04b8", "0x0120"]
status = "good"
comment = "Requires firmware esfw3e.bin."

[mfg.model]
model = "Perfection 1670"
interface = "USB"
usbid = ["0x04b8", "0x011f"]
status = "good"
comment = "Requires firmware esfw30.bin."

[mfg.model]
model = "Perfection 2480 PHOTO"
interface = "USB"
usbid = ["0x04b8", "0x0121"]
status = "good"
comment = "Requires firmware esfw41.bin."

[mfg.model]
model = "Perfection 2580 PHOTO"
interface = "USB"
status = "basic"
usbid = ["0x04b8", "0x0121"]
comment = "Requires firmware esfw41.bin, film scanning unit unsupported."

[mfg.model]
model = "Perfection 3490 PHOTO"
interface = "USB"
usbid = ["0x04b8", "0x0122"]
status = "good"
comment = "Requires firmware esfw51.bin."

[mfg.model]
model = "Perfection 3590 PHOTO"
interface = "USB"
usbid = ["0x04b8", "0x0122"]
status = "basic"
comment = "Requires firmware esfw52.bin, film scanning unit unsupported."

[mfg.model]
model = "Stylus CX-1500"
interface = "USB"
usbid = ["0x04b8", "0x080c"]
status = "good"

# comment = and url = specifiers are optional after :mfg, :model, :desc,
#  and at the top-level.
