#
# SANE Backend specification file
#

[backend]
backend = "artec_eplus48u"
version = "unmaintained"
manpage = "sane-artec_eplus48u"
# url = "http://www.angelfire.com/linux/crapsite/"
devicetype = "scanner"

[mfg]
mfg = "Artec/Ultima"
url = "http://www.artecusa.com/"

[mfg.model]
model = "E+ 48U"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4003"]
comment = "CIS scanner based on the GT6816 chip. Apparently all other devices are re-badged Artec scanners."

[mfg.model]
model = "E+ Pro"
status = "minimal"
interface = "USB"
usbid = ["0x05d8", "0x4004"]
comment = "Works up to 600dpi, but not 1200. Needs better calibration. See bug #310490"


[mfg]
mfg = "Medion/Lifetec/Tevion/Cytron"
url = "http://www.medion.com"
comment = "Sold by Aldi and Tchibo."

[mfg.model]
model = "MD9693"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4003"]

[mfg.model]
model = "MD9705"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4003"]

[mfg.model]
model = "MD4394"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4003"]
comment = "Only scanners with product id 0x4003 will work# try the gt68xx backend, if your scanner has product id 0x4002 "


[mfg]
mfg = "Trust"
url = "http://www.trust-site.com"

[mfg.model]
model = "Easy Webscan 19200"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4006"]

[mfg.model]
model = "240H Easy Webscan Gold"
status = "basic"
interface = "USB"
usbid = ["0x05d8", "0x4007"]
comment = "Works up to 600 dpi"


[mfg]
mfg = "Memorex"
url = "http://www.artecusa.com/"

[mfg.model]
model = "MEM 48U"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4005"]


[mfg]
mfg = "Microstar"
url = "http://www.microstar.de/"

[mfg.model]
model = "MR 9791"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4003"]


[mfg]
mfg = "UMAX"
url = "http://www.umax.com/"
url = "http://www.umax.com.tw/"
url = "http://www.umax.de/en"
url = "http://www.umax-europe.com"
url = "http://www.umaxjapan.co.jp"
url = "http://www.umax.com.cn"

[mfg.model]
model = "AstraSlim SE"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4009"]

[mfg.model]
model = "AstraSlim 1200 SE"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4010"]


[mfg]
mfg = "Yakumo"
url = "http://www.yakumo.com/"

[mfg.model]
model = "Scan50"
status = "good"
interface = "USB"
usbid = ["0x05d8", "0x4011"]
