#
# SANE Backend specification file for coolscan2
#
# It's basically emacs-lisp --- so ";" indicates comment to end of line.
# All syntactic elements are keyword tokens, followed by a string or
#  keyword argument, as specified.
#
# ":backend" *must* be specified.
# All other information is optional (but what good is the file without it?).
#

[backend]
backend = "coolscan3"
version = "1.0.0 (unmaintained)"
manpage = "sane-coolscan3"

devicetype = "scanner"
[mfg]
mfg = "Nikon"
url = "http://www.nikon.com/"

[mfg.model]
model = "LS 30"
interface = "SCSI"
status = "complete"

[mfg.model]
model = "Coolscan III"
interface = "SCSI"
status = "complete"
comment = "Rebadged LS 30?"

[mfg.model]
model = "LS 40 ED"
interface = "USB"
usbid = ["0x04b0", "0x4000"]
status = "complete"

[mfg.model]
model = "Coolspan IV"
interface = "USB"
usbid = ["0x04b0", "0x4000"]
status = "complete"
comment = "Rebadged LS 40?"

[mfg.model]
model = "LS 50 ED"
url = "unsupported/nikon-ls50-ed.html"
interface = "USB"
usbid = ["0x04b0", "0x4001"]
status = "minimal"

[mfg.model]
model = "Coolscan V ED"
url = "unsupported/nikon-ls50-ed.html"
interface = "USB"
usbid = ["0x04b0", "0x4001"]
status = "minimal"
comment = "Rebadged LS 50?"

[mfg.model]
model = "LS 2000"
interface = "SCSI"
status = "good"

[mfg.model]
model = "LS 4000 ED"
interface = "IEEE-1394"
status = "good"
comment = "needs linux kernel 2.4.19 or later"

[mfg.model]
model = "Super Coolscan LS-5000 ED"
url = "unsupported/nikon-ls5000-ed.html"
interface = "USB"
usbid = ["0x04b0", "0x4002"]
status = "untested"
comment = "May work, similar to LS 50 ED, but untested. Please tell us if it works."

[mfg.model]
model = "LS 8000 ED"
interface = "IEEE-1394"
status = "good"
comment = "needs linux kernel 2.4.19 or later"

# comment = and url = specifiers are optional after :mfg, :model, :desc,
#  and at the top-level.
