#
# SANE Backend specification file
#
# It's basically emacs-lisp --- so ";" indicates comment to end of line.
# All syntactic elements are keyword tokens, followed by a string or
#  keyword argument, as specified.
#
# ":backend" *must* be specified.
# All other information is optional (but what good is the file without it?).
#

[backend]
backend = "canon_dr"    # name of backend
url = "http://www.thebility.com/canon/"
version = "60"                    # version of backend
manpage = "sane-canon_dr"         # name of manpage (if it exists)
comment = "Backend updated for SANE release 1.0.32, see sane-canon_dr manpage"
devicetype = "scanner"             # start of a list of devices....
                                 # other types:  :stillcam, :vidcam,
                                 #               :meta, :api

[mfg]
mfg = "Canon"                   # name a manufacturer
url = "http://www.canon.com/"

# ==================================================
[mfg.model]
model = "CR-25"
interface = "USB"
usbid = ["0x1083", "0x161a"]
status = "untested"
comment = "Please test!"

[mfg.model]
model = "CR-50"
interface = "USB"
# usbid = ["0x1083", "0x"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "CR-55"
interface = "USB"
usbid = ["0x1083", "0x160c"]
status = "untested"
comment = "Please test!"

[mfg.model]
model = "CR-80"
interface = "USB"
# usbid = ["0x1083", "0x"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "CR-135i"
interface = "USB SCSI"
usbid = ["0x1083", "0x1639"]
status = "untested"
comment = "Please test!"

[mfg.model]
model = "CR-180"
interface = "USB SCSI"
usbid = ["0x04a9", "0x1602"]
status = "untested"
comment = "Please test!"

[mfg.model]
model = "CR-180II"
interface = "USB SCSI"
usbid = ["0x04a9", "0x1602"]
status = "untested"
comment = "Same as CR-180? Please test!"

[mfg.model]
model = "CR-190i"
interface = "USB SCSI"
usbid = ["0x1083", "0x162b"]
status = "untested"
comment = "Please test!"

[mfg.model]
model = "DR-1210C"
interface = "USB"
usbid = ["0x04a9", "0x2222"]
status = "untested"
comment = "Older version? Please test!"

[mfg.model]
model = "DR-1210C"
interface = "USB"
usbid = ["0x1083", "0x160f"]
status = "untested"
comment = "Later version? Please test!"

[mfg.model]
model = "DR-2010C"
interface = "USB"
usbid = ["0x1083", "0x161b"]
status = "complete"
comment = "Hardware provides: Gray/Color, Simplex/Duplex, Full-width, 300/600dpi horizontal. Driver provides: Binary, Despeckle, Deskew, Cropping, Calibration, other resolutions."

[mfg.model]
model = "DR-2010M"
interface = "USB"
status = "complete"
comment = "DR-2010C with a different label, same USB IDs"

[mfg.model]
model = "DR-2050C"
interface = "USB"
usbid = ["0x04a9", "0x160a"]
status = "complete"
comment = "Hardware provides: Gray/Color, Simplex/Duplex, Full-width. Driver provides: Binary, Despeckle, Deskew, Cropping, Calibration."

[mfg.model]
model = "DR-2050SP"
interface = "USB"
usbid = ["0x04a9", "0x160a"]
status = "untested"
comment = "Same as DR-2050C? Please test!"

[mfg.model]
model = "DR-2080C"
interface = "USB SCSI"
usbid = ["0x04a9", "0x1601"]
status = "complete"
comment = "Hardware provides: Gray/Color, Simplex/Duplex, Full-width. Driver provides: Binary, Despeckle, Deskew, Cropping, Calibration"

[mfg.model]
model = "DR-2510C"
interface = "USB"
usbid = ["0x1083", "0x1617"]
status = "complete"
comment = "Hardware provides: Gray/Color, Simplex/Duplex, Full-width, 300/600dpi horizontal. Driver provides: Binary, Despeckle, Deskew, Cropping, Calibration, other resolutions"

[mfg.model]
model = "DR-2510M"
interface = "USB"
status = "untested"
comment = "Mac version of DR-2510C? Please test!"

[mfg.model]
model = "DR-2580C"
interface = "USB SCSI"
usbid = ["0x04a9", "0x1608"]
status = "complete"
comment = "Hardware provides: Gray/Color, Simplex/Duplex, Full-width. Driver provides: Binary, Despeckle, Deskew, Cropping, Calibration"

[mfg.model]
model = "DR-3010C"
interface = "USB"
usbid = ["0x1083", "0x161d"]
status = "good"
comment = "Minimal testing, settings copied from DR-2510C"

[mfg.model]
model = "DR3020"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "DR-3020C"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "DR-3060"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "DR-3080C"
interface = "SCSI"
status = "untested"
comment = "Almost works, need to investigate traces from windows driver"

[mfg.model]
model = "DR-3080CII"
interface = "USB SCSI"
usbid = ["0x04a9", "0x1609"]
status = "untested"
comment = "Almost works, need to investigate traces from windows driver"

[mfg.model]
model = "DR-4010C"
interface = "USB"
usbid = ["0x1083", "0x1614"]
status = "good"
comment = "Binary/HT/Gray/Color, Simplex/Duplex working. Multistream unsupported."

[mfg.model]
model = "DR4080U"
interface = "USB"
# usbid = ["0x1083", "0x1614"]
status = "untested"
comment = "Please test!"

[mfg.model]
model = "DR-4580U"
interface = "USB"
# usbid = ["0x1083", "0x1614"]
status = "untested"
comment = "Please test!"

[mfg.model]
model = "DR-5010C"
interface = "USB"
usbid = ["0x04a9", "0x1606"]
status = "basic"
comment = "ADF and Duplex work, needs more testing"

[mfg.model]
model = "DR-5020"
interface = "SCSI"
status = "good"
comment = "LineArt, Duplex working, cannot read buttons or screen?"

[mfg.model]
model = "DR-5060F"
interface = "SCSI"
status = "basic"
comment = "Grayscale works, LineArt might"

[mfg.model]
model = "DR-5080C"
interface = "SCSI"
status = "untested"
comment = "Please test!"

[mfg.model]
model = "DR-6010C"
interface = "USB SCSI"
usbid = ["0x1083", "0x1626"]
status = "untested"
comment = "Please test!"

[mfg.model]
model = "DR-6030C"
interface = "USB SCSI"
usbid = ["0x1083", "0x1638"]
status = "untested"
comment = "Please test!"

[mfg.model]
model = "DR-6050C"
interface = "USB SCSI"
usbid = ["0x1083", "0x1624"]
status = "good"
comment = "Simplex, duplex, all resolutions, binary/ht/gray working.  Can't wake from stand-by mode"

[mfg.model]
model = "DR-6080"
interface = "USB SCSI"
usbid = ["0x04a9", "0x1607"]
status = "good"
comment = "Simplex, duplex, all resolutions, binary/ht/gray, async mode, dropout-color, multifeed/staple detection, deskew, buttons and JPEG working. Imprinter, barcode, custom gamma and multistream unsupported"

[mfg.model]
model = "DR-7080C"
interface = "USB SCSI"
usbid = ["0x04a9", "0x1604"]
status = "good"
comment = "ADF and flatbed work"

[mfg.model]
model = "DR-7090C"
interface = "USB SCSI"
usbid = ["0x1083", "0x1620"]
status = "good"
comment = "ADF and flatbed work"

[mfg.model]
model = "DR-7550C"
interface = "USB SCSI"
usbid = ["0x1083", "0x1623"]
status = "untested"
comment = "Assumed compatible with DR-6050C"

[mfg.model]
model = "DR-7580"
interface = "USB SCSI"
usbid = ["0x04a9", "0x160b"]
status = "good"
comment = "Simplex, duplex, all resolutions, binary/ht/gray, async mode, dropout-color, multifeed/staple detection, deskew, buttons and JPEG working. Imprinter, barcode, custom gamma and multistream unsupported"

[mfg.model]
model = "DR-9050C"
interface = "USB SCSI"
usbid = ["0x1083", "0x1622"]
status = "good"
comment = "Simplex, duplex, all resolutions, binary/ht/gray working.  Can't wake from stand-by mode"

[mfg.model]
model = "DR-9080C"
interface = "USB SCSI"
usbid = ["0x04a9", "0x1603"]
status = "good"
comment = "Simplex, duplex, all resolutions, binary/ht/gray/color, async mode, dropout-color, multifeed/staple detection, deskew, buttons and JPEG working. Imprinter, barcode, custom gamma and multistream unsupported"

[mfg.model]
model = "DR-X10C"
interface = "USB SCSI"
usbid = ["0x1083", "0x1618"]
status = "good"
comment = "Simplex, duplex, all resolutions, binary/ht/gray/color, async mode, dropout-color, multifeed/staple detection, deskew, autocrop working. Imprinter, barcode, custom gamma and multistream unsupported"

[mfg.model]
model = "DR-C120"
interface = "USB"
usbid = ["0x1083", "0x1651"]
status = "basic"
comment = "Gray and color work, may always scan in duplex, lower edge may be cropped"

[mfg.model]
model = "DR-C125"
interface = "USB"
usbid = ["0x1083", "0x1640"]
status = "good"

[mfg.model]
model = "DR-C130"
interface = "USB"
usbid = ["0x1083", "0x164a"]
status = "untested"
comment = "May be compatible with DR-C120"

[mfg.model]
model = "DR-C225"
interface = "USB"
usbid = ["0x1083", "0x1658"]
status = "basic"
comment = "Calibration is poor, grayscale mode may crash. DR-C225ii is the same device."

[mfg.model]
model = "DR-F120"
interface = "USB"
usbid = ["0x1083", "0x1654"]
status = "basic"
comment = "Flatbed not working. ADF working. Simplex+duplex, all resolutions <= 600, gray/color, calibration poor."

[mfg.model]
model = "DR-G1100"
interface = "USB"
usbid = ["0x1083", "0x1650"]
status = "good"

[mfg.model]
model = "DR-G1130"
interface = "USB"
usbid = ["0x1083", "0x164f"]
status = "untested"

[mfg.model]
model = "DR-M140"
interface = "USB"
usbid = ["0x1083", "0x163f"]
status = "good"

[mfg.model]
model = "DR-M160"
interface = "USB"
usbid = ["0x1083", "0x163e"]
status = "good"

[mfg.model]
model = "DR-M160II"
interface = "USB"
# usbid = ["0x1083", "0x"
status = "untested"

[mfg.model]
model = "DR-M1060"
interface = "USB"
usbid = ["0x1083", "0x1657"]
status = "untested"

[mfg.model]
model = "P-150"
interface = "USB"
# usbid = ["0x1083", "0x162c"]
status = "untested"
comment = "Same as P-150M?"

[mfg.model]
model = "P-150M"
interface = "USB"
usbid = ["0x1083", "0x162c"]
status = "good"

[mfg.model]
model = "P-201"
interface = "USB"
usbid = ["0x1083", "0x1652"]
status = "untested"

[mfg.model]
model = "DR-P208"
interface = "USB"
usbid = ["0x1083", "0x164b"]
status = "untested"
comment = "Same as P-208?"

[mfg.model]
model = "P-208"
interface = "USB"
usbid = ["0x1083", "0x164c"]
status = "basic"
comment = "All modes and resolutions working, but calibration is poor."

[mfg.model]
model = "P-208"
interface = "USB"
usbid = ["0x1083", "0x164e"]
status = "basic"
comment = "This is the same device as the 0x164c P-208, but the mode switch on the scanner is in the wrong position, you must move the switch."

[mfg.model]
model = "DR-P208II"
interface = "USB"
usbid = ["0x1083", "0x165d"]
status = "untested"

[mfg.model]
model = "P-208II"
interface = "USB"
usbid = ["0x1083", "0x165f"]
status = "basic"
comment = "Simplex+duplex, all resolutions <= 600, gray/color, calibration poor."

[mfg.model]
model = "P-208II"
interface = "USB"
usbid = ["0x1083", "0x1660"]
status = "basic"
comment = "This is the same device as the 0x165f P-208II, but the mode switch on the scanner is in the wrong position, you must move the switch."

[mfg.model]
model = "DR-P215"
interface = "USB"
usbid = ["0x1083", "0x1641"]
status = "untested"
comment = "Same as P-215?"

[mfg.model]
model = "P-215"
interface = "USB"
usbid = ["0x1083", "0x1646"]
status = "basic"
comment = "All modes and resolutions working, but calibration is poor. Card reader slot not working."

[mfg.model]
model = "P-215"
interface = "USB"
usbid = ["0x1083", "0x1647"]
status = "basic"
comment = "This is the same device as the 0x1646 P-215, but the mode switch on the scanner is in the wrong position, you must move the switch."

[mfg.model]
model = "DR-P215II"
interface = "USB"
usbid = ["0x1083", "0x1659"]
status = "untested"

[mfg.model]
model = "P-215II"
interface = "USB"
usbid = ["0x1083", "0x165b"]
status = "untested"

[mfg.model]
model = "FSU-201"
interface = "USB"
usbid = ["0x1083", "0x1648"]
status = "untested"
