#
# SANE Backend description file for Plustek backend (USB only)
#

[backend]
backend = "plustek"
version = "0.52"
manpage = "sane-plustek"

devicetype = "scanner"

# * Plustek **********************************************************************************

[mfg]
mfg = "Plustek"
url = "http://www.plustek.de/"
url = "http://www.plustek.com/"

[mfg.model]
model = "OpticPro U12"
interface = "USB"
usbid = ["0x07b3", "0x0010"]
status = "complete"
comment = "NOTE: Devices with product ID 0x0001 are not supported!"

[mfg.model]
model = "OpticPro UT12"
interface = "USB"
usbid = ["0x07b3", "0x0013"]
status = "complete"

[mfg.model]
model = "OpticPro UT12"
interface = "USB"
usbid = ["0x07b3", "0x0017"]
status = "complete"
comment = "Note: Devices with product ID 0x0001 are not supported!"

[mfg.model]
model = "OpticPro UT16"
interface = "USB"
usbid = ["0x07b3", "0x0017"]
status = "complete"

[mfg.model]
model = "OpticPro U24"
interface = "USB"
usbid = ["0x07b3", "0x0011"]
status = "complete"

[mfg.model]
model = "OpticPro U24"
interface = "USB"
usbid = ["0x07b3", "0x0015"]
status = "complete"

[mfg.model]
model = "OpticPro UT24"
interface = "USB"
usbid = ["0x07b3", "0x0017"]
status = "complete"

# * Genius/KYE *******************************************************************************************

[mfg]
mfg = "Genius"
url = "http://www.geniusnet.com.tw/"

[mfg.model]
model = "Colorpage HR6 V2"
interface = "USB"
usbid = ["0x0458", "0x2007"]
status = "complete"

[mfg.model]
model = "Colorpage HR6 V2"
interface = "USB"
usbid = ["0x0458", "0x2008"]
status = "complete"

[mfg.model]
model = "Colorpage HR7"
interface = "USB"
usbid = ["0x0458", "0x2013"]
status = "complete"

[mfg.model]
model = "Colorpage HR6A"
interface = "USB"
usbid = ["0x0458", "0x2009"]
status = "untested"

[mfg.model]
model = "Colorpage HR7LE"
interface = "USB"
usbid = ["0x0458", "0x2015"]
status = "untested"

[mfg.model]
model = "Colorpage HR6X"
interface = "USB"
usbid = ["0x0458", "0x2016"]
status = "untested"

# * MUSTEK ***********************************************************************************

[mfg]
mfg = "Mustek"
url = "http://www.mustek.com/"

[mfg.model]
model = "BearPaw 1200"
interface = "USB"
usbid = ["0x0400", "0x1000"]
status = "complete"
comment = "both product versions are supported, see backends' man-page"

[mfg.model]
model = "BearPaw 1200"
interface = "USB"
usbid = ["0x0400", "0x1001"]
status = "complete"
comment = "both product versions are supported, see backends' man-page"

[mfg.model]
model = "BearPaw 2400"
interface = "USB"
usbid = ["0x0400", "0x1001"]
status = "complete"

# * Hewlett-Packard **************************************************************************

[mfg]
mfg = "Hewlett-Packard"
url = "http://www.hp.com/"

[mfg.model]
model = "ScanJet 2100C"
interface = "USB"
usbid = ["0x03f0", "0x0505"]
status = "complete"

[mfg.model]
model = "ScanJet 2200C"
interface = "USB"
usbid = ["0x03f0", "0x0605"]
status = "complete"

# * EPSON *******************************************************************************************

[mfg]
mfg = "Epson"
url = "http://www.epson.com/"

[mfg.model]
model = "Perfection 1250"
interface = "USB"
usbid = ["0x04b8", "0x010f"]
status = "complete"

[mfg.model]
model = "Perfection 1250Photo"
interface = "USB"
usbid = ["0x04b8", "0x010f"]
status = "good"
comment = "TPA scans not perfect"

[mfg.model]
model = "Perfection 1260"
interface = "USB"
usbid = ["0x04b8", "0x011d"]
status = "complete"

[mfg.model]
model = "Perfection 1260Photo"
interface = "USB"
usbid = ["0x04b8", "0x011d"]
status = "good"
comment = "TPA scans not perfect"

# * UMAX *************************************************************************************

[mfg]
mfg = "Umax"
url = "http://www.umax.com/"

[mfg.model]
model = "UMAX 3400"
interface = "USB"
usbid = ["0x1606", "0x0050"]
status = "complete"
comment = "there are some UMAX 3400 outside the U.S. which are not supported, as they use another chipset than the LM983x"

[mfg.model]
model = "UMAX 3400"
interface = "USB"
usbid = ["0x1606", "0x0060"]
status = "complete"
comment = "there are some UMAX 3400 outside the U.S. which are not supported, as they use another chipset than the LM983x"

[mfg.model]
model = "UMAX Astranet ia101"
interface = "USB"
usbid = ["0x1606", "0x0060"]
status = "complete"
comment = "seems to be a renamed UMAX 3400"

[mfg.model]
model = "UMAX 3450"
interface = "USB"
usbid = ["0x1606", "0x0060"]
status = "complete"

[mfg.model]
model = "UMAX 5400"
interface = "USB"
usbid = ["0x1606", "0x0160"]
status = "complete"

# * COMPAQ ******************************************************************************************

[mfg]
mfg = "Compaq"
url = "http://www.compaq.com/"

[mfg.model]
model = "S4-100"
interface = "USB"
usbid = ["0x049f", "0x001a"]
status = "complete"
comment = "Identical to UMAX 3400"


# * CANON *******************************************************************************************

[mfg]
mfg = "Canon"
url = "http://www.canon.com/"

[mfg.model]
model = "CanoScan N650U"
interface = "USB"
usbid = ["0x04a9", "0x2206"]
status = "complete"

[mfg.model]
model = "CanoScan N656U"
interface = "USB"
usbid = ["0x04a9", "0x2206"]
status = "complete"
comment = "Identical to CanoScan N650U"

[mfg.model]
model = "CanoScan N1220U"
interface = "USB"
usbid = ["0x04a9", "0x2207"]
status = "complete"

[mfg.model]
model = "CanoScan N670U"
interface = "USB"
usbid = ["0x04a9", "0x220d"]
status = "complete"

[mfg.model]
model = "CanoScan N676U"
interface = "USB"
usbid = ["0x04a9", "0x220d"]
status = "complete"
comment = "Identical to CanoScan N670U"

[mfg.model]
model = "CanoScan LiDE 20"
interface = "USB"
usbid = ["0x04a9", "0x220d"]
status = "complete"
comment = "Identical to CanoScan N670U"

[mfg.model]
model = "CanoScan N1240U"
interface = "USB"
usbid = ["0x04a9", "0x220e"]
status = "complete"

[mfg.model]
model = "CanoScan LiDE 30"
interface = "USB"
usbid = ["0x04a9", "0x220e"]
status = "complete"
comment = "Identical to CanoScan N1240U"

[mfg.model]
model = "CanoScan LiDE 25"
interface = "USB"
usbid = ["0x04a9", "0x2220"]
status = "good"

[mfg.model]
model = "CanoScan D660U"
interface = "USB"
usbid = ["0x04a9", "0x2208"]
status = "good"
comment = "TPA scans not perfect"

# * SYSCAN *******************************************************************************************

[mfg]
mfg = "Syscan"
url = "http://www.syscaninc.com/"

[mfg.model]
model = "TravelScan 460/464"
interface = "USB"
usbid = ["0x0a82", "0x4600"]
status = "complete"

[mfg.model]
model = "TravelScan 662"
interface = "USB"
usbid = ["0x0a82", "0x6620"]
status = "complete"

# * SYSCAN *******************************************************************************************

[mfg]
mfg = "Ambir"

[mfg.model]
model = "Visigo A4"
interface = "USB"
usbid = ["0x0a82", "0x4600"]
status = "complete"
comment = "Rebaged Travelscan 464"

# * Portable Peripheral Co., Ltd. ********************************************************************

[mfg]
mfg = "Portable Peripheral Co., Ltd."
url = "http://www.pandp.com.tw/"

[mfg.model]
model = "Q-Scan USB001 (A4 portable scanner)"
interface = "USB"
usbid = ["0x0a53", "0x1000"]
status = "complete"

[mfg.model]
model = "Q-Scan USB201 (A6 portable scanner)"
interface = "USB"
usbid = ["0x0a53", "0x2000"]
status = "good"

# * Visioneer ****************************************************************************************

[mfg]
mfg = "Visioneer"
url = "http://www.visioneer.com/"

[mfg.model]
model = "Strobe XP 100"
interface = "USB"
usbid =  "0x04a7", "0x0427"]
status = "basic"
